---
id: rabbit-slide-kenhys-mroonga-meetup-20140629
base_name: mroonga-meetup-20140629
tags:
- mroonga
presentation_date: 
version: 1.0.0
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: HAYASHI Kentaro
  email: hayashi@clear-code.com
  rubygems_user: kenhys
  slideshare_user: kenhys
  speaker_deck_user: 
